import importlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import textwrap
import tomllib

from fastapi import FastAPI
from packaging.requirements import Requirement
from packaging.version import InvalidVersion, Version
import pytest

from twinops import main_v2


_MANIFEST_HASH = "sha256:fe2cbd7e1b576f04b2c6380e41ecb7c97df7faa5084c39c4b0d16db786afe7f0"
_MODEL_HASH = "sha256:68d00121edbf8c4c01cf7cd231cd57c4c8eff25661135494e3c791ca78e562ba"
_DEPLOY_FORBIDDEN_DISTRIBUTIONS = {
    "rarfile",
    "scikit-learn",
    "scipy",
    "sklearn",
}
_REQUIREMENT_NAME = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^]]+\])?")
_SHA256_HASH = re.compile(r"^--hash=sha256:[0-9a-f]{64}$")


def _normalized_requirement_name(requirement: str) -> str:
    match = _REQUIREMENT_NAME.match(requirement)
    assert match is not None, f"invalid requirement: {requirement!r}"
    return re.sub(r"[-_.]+", "-", match.group(1)).lower()


def _assert_deploy_lock_contract(input_text: str, lock_text: str) -> None:
    input_requirements = [
        line.strip()
        for line in input_text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    direct_requirements: dict[str, Requirement] = {}
    for requirement_text in input_requirements:
        requirement = Requirement(requirement_text)
        name = _normalized_requirement_name(requirement.name)
        assert name not in direct_requirements, f"duplicate direct requirement: {name}"
        assert requirement.url is None, f"URL requirement is not reproducible: {name}"
        assert requirement.marker is None, f"marker is not allowed in deploy input: {name}"
        assert requirement.specifier, f"direct requirement is unconstrained: {name}"
        direct_requirements[name] = requirement
    direct_names = set(direct_requirements)

    required_command_fragments = (
        "This file was autogenerated by uv",
        "requirements.in",
        "--python-version 3.12",
        "--python-platform x86_64-unknown-linux-gnu",
        "--generate-hashes",
        "--only-binary :all:",
        "--output-file requirements.txt",
    )
    for fragment in required_command_fragments:
        assert fragment in lock_text, f"lock command is missing {fragment!r}"

    hashes_by_distribution: dict[str, list[str]] = {}
    versions_by_distribution: dict[str, Version] = {}
    current_distribution: str | None = None
    for raw_line in lock_text.splitlines():
        line = raw_line.strip().removesuffix("\\").strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("--hash="):
            assert current_distribution is not None
            assert _SHA256_HASH.fullmatch(line), f"invalid lock hash: {line!r}"
            hashes_by_distribution[current_distribution].append(line)
            continue

        distribution_text, separator, version_text = line.partition("==")
        assert separator and distribution_text and version_text, (
            f"unlocked distribution: {line!r}"
        )
        try:
            locked_version = Version(version_text)
        except InvalidVersion as error:
            raise AssertionError(f"invalid locked version: {version_text!r}") from error
        current_distribution = _normalized_requirement_name(distribution_text)
        assert current_distribution not in hashes_by_distribution, (
            f"duplicate locked distribution: {current_distribution}"
        )
        hashes_by_distribution[current_distribution] = []
        versions_by_distribution[current_distribution] = locked_version

    assert hashes_by_distribution, "deploy lock is empty"
    for distribution, hashes in hashes_by_distribution.items():
        assert hashes, f"locked distribution has no hash: {distribution}"

    locked_names = set(hashes_by_distribution)
    missing_direct = direct_names - locked_names
    assert not missing_direct, f"deploy lock is stale: missing {sorted(missing_direct)}"
    for name, requirement in direct_requirements.items():
        locked_version = versions_by_distribution[name]
        assert requirement.specifier.contains(locked_version, prereleases=True), (
            f"locked {name} {locked_version} does not satisfy {requirement.specifier}"
        )
    forbidden = _DEPLOY_FORBIDDEN_DISTRIBUTIONS & (direct_names | locked_names)
    assert not forbidden, f"training/extraction dependency in deploy lock: {sorted(forbidden)}"


def test_vercel_python_runtime_is_pinned_for_binary_wheels():
    repository_root = Path(__file__).parents[4]

    assert (repository_root / ".python-version").read_text(encoding="utf-8").strip() == "3.12"


def test_vercel_requirements_only_include_runtime_science_dependencies():
    repository_root = Path(__file__).parents[4]
    input_text = (repository_root / "requirements.in").read_text(encoding="utf-8")
    requirements = {
        line.strip()
        for line in input_text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }

    assert "joblib>=1.4,<2" in requirements
    assert not any(line.startswith("scipy") for line in requirements)
    assert not any(line.startswith("scikit-learn") for line in requirements)


def test_vercel_requirements_lock_every_runtime_distribution_by_hash():
    repository_root = Path(__file__).parents[4]
    input_text = (repository_root / "requirements.in").read_text(encoding="utf-8")
    lock_text = (repository_root / "requirements.txt").read_text(encoding="utf-8")

    _assert_deploy_lock_contract(input_text, lock_text)


def test_deploy_lock_contract_rejects_an_input_missing_from_the_lock():
    input_text = "joblib>=1.4,<2\nhttpx>=0.27,<1\n"
    lock_text = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in --python-version 3.12 --python-platform x86_64-unknown-linux-gnu --generate-hashes --only-binary :all: --output-file requirements.txt
joblib==1.5.3 \\
    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
"""

    with pytest.raises(AssertionError, match="stale"):
        _assert_deploy_lock_contract(input_text, lock_text)


@pytest.mark.parametrize(
    "incompatible_input",
    ("joblib>=1.6,<2\n", "joblib>=1,<1.5\n"),
)
def test_deploy_lock_contract_rejects_a_pin_outside_the_declared_range(
    incompatible_input,
):
    lock_text = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in --python-version 3.12 --python-platform x86_64-unknown-linux-gnu --generate-hashes --only-binary :all: --output-file requirements.txt
joblib==1.5.3 \\
    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
"""

    with pytest.raises(AssertionError, match="does not satisfy"):
        _assert_deploy_lock_contract(incompatible_input, lock_text)


def test_deploy_lock_contract_rejects_unhashed_and_forbidden_distributions():
    input_text = "joblib>=1.4,<2\n"
    unhashed_lock = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in --python-version 3.12 --python-platform x86_64-unknown-linux-gnu --generate-hashes --only-binary :all: --output-file requirements.txt
joblib==1.5.3 \\
    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa \\
    --hash=sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
anyio==4.14.2
"""
    forbidden_lock = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in --python-version 3.12 --python-platform x86_64-unknown-linux-gnu --generate-hashes --only-binary :all: --output-file requirements.txt
joblib==1.5.3 \\
    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
rarfile==4.2 \\
    --hash=sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
"""

    wrong_target_lock = forbidden_lock.replace(
        "--python-platform x86_64-unknown-linux-gnu",
        "--python-platform x86_64-pc-windows-msvc",
    ).replace("rarfile==4.2", "anyio==4.14.2")

    for broken_lock in (unhashed_lock, forbidden_lock, wrong_target_lock):
        with pytest.raises(AssertionError):
            _assert_deploy_lock_contract(input_text, broken_lock)


def test_twinops_declares_joblib_as_a_direct_runtime_dependency():
    repository_root = Path(__file__).parents[4]
    project = tomllib.loads(
        (repository_root / "services/twinops/pyproject.toml").read_text(
            encoding="utf-8"
        )
    )

    assert "joblib>=1.4,<2" in project["project"]["dependencies"]


def test_vercel_function_excludes_local_secrets_and_nonruntime_files():
    repository_root = Path(__file__).parents[4]
    config = json.loads((repository_root / "vercel.json").read_text(encoding="utf-8"))
    exclude_files = config["functions"]["api/index.py"]["excludeFiles"]

    for pattern in (
        ".env*",
        ".superpowers/**",
        "**/{.agents,test,tests}/**",
        "{contracts,docs,evals,notebooks,scripts,src,tools}/**",
        "dist/**",
        "real-forzy/source-summary.json",
    ):
        assert pattern in exclude_files


def test_vercel_upload_context_ignores_agent_metadata():
    repository_root = Path(__file__).parents[4]
    ignore_patterns = {
        line.strip()
        for line in (repository_root / ".vercelignore")
        .read_text(encoding="utf-8")
        .splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }

    assert ".agents/**" in ignore_patterns
    assert ".superpowers/**" in ignore_patterns
    assert "**/.pytest_cache" in ignore_patterns
    assert "skills-lock.json" in ignore_patterns


def test_real_runtime_assessment_does_not_import_training_dependencies():
    expected = _run_real_runtime_assessment(block_training_dependencies=False)
    runtime_only = _run_real_runtime_assessment(block_training_dependencies=True)

    assert runtime_only == expected


def test_vercel_entrypoint_exposes_fastapi_without_external_io(monkeypatch):
    def forbidden_io(*args, **kwargs):
        raise AssertionError("Vercel entrypoint import must not perform external I/O")

    monkeypatch.setenv("VERCEL", "1")
    monkeypatch.setenv("TWINOPS_STARTUP_VALIDATE_ONLY", "1")
    monkeypatch.setenv("TWINOPS_UPSTREAM_BASE_URL", "https://upstream.invalid")
    monkeypatch.setenv(
        "DATABASE_URL",
        "postgresql://runtime@runtime-pooler.invalid/twinops?sslmode=require",
    )
    monkeypatch.setenv("TWINOPS_ML_ARTIFACT_PATH", "artifacts/ml/real-forzy")
    monkeypatch.setenv("TWINOPS_ML_MANIFEST_HASH", f"sha256:{'1' * 64}")
    monkeypatch.setenv("TWINOPS_ML_MODEL_HASH", f"sha256:{'2' * 64}")
    monkeypatch.setattr(main_v2.PostgresTelemetryRepository, "initialize", forbidden_io)
    monkeypatch.setattr(main_v2.httpx, "AsyncClient", forbidden_io)
    monkeypatch.setattr(main_v2, "load_assessment_scorer", forbidden_io)
    sys.modules.pop("api.index", None)

    module = importlib.import_module("api.index")

    assert isinstance(module.app, FastAPI)


def test_vercel_entrypoint_bootstraps_bundled_twinops_source():
    repository_root = Path(__file__).parents[4]
    command = """
import runpy
import sys

sys.path = [
    item for item in sys.path
    if not item.replace('\\\\', '/').endswith('/services/twinops/src')
]
runpy.run_path('api/index.py')
print('imported')
"""
    env = {
        **os.environ,
        "VERCEL": "1",
        "TWINOPS_UPSTREAM_BASE_URL": "https://upstream.invalid",
        "DATABASE_URL": (
            "postgresql://runtime@runtime-pooler.invalid/twinops?sslmode=require"
        ),
    }

    completed = subprocess.run(
        [sys.executable, "-c", command],
        cwd=repository_root,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout.strip() == "imported"


def _run_real_runtime_assessment(*, block_training_dependencies: bool) -> dict:
    repository_root = Path(__file__).parents[4]
    command = textwrap.dedent(
        """
        from datetime import datetime, timedelta, timezone
        import json
        from pathlib import Path
        import sys
        """
    )
    if block_training_dependencies:
        command += textwrap.dedent(
            """
            import importlib.abc

            class TrainingDependencyBlocker(importlib.abc.MetaPathFinder):
                def find_spec(self, fullname, path, target=None):
                    if fullname.partition('.')[0] in {'scipy', 'sklearn'}:
                        raise ModuleNotFoundError(
                            f'training-only dependency imported: {fullname}'
                        )
                    return None

            sys.meta_path.insert(0, TrainingDependencyBlocker())
            """
        )
    command += textwrap.dedent(
        f"""
        from twinops.contracts.models import CanonicalSensorReading
        from twinops.ml.runtime import load_assessment_scorer

        root = Path.cwd()
        scorer = load_assessment_scorer(
            root / 'artifacts' / 'ml' / 'real-forzy',
            expected_manifest_hash='{_MANIFEST_HASH}',
            expected_model_hash='{_MODEL_HASH}',
        )
        base = datetime(2026, 8, 12, 13, 0, tzinfo=timezone.utc)
        samples = []
        for second in range(4):
            instant = base + timedelta(seconds=second)
            timestamp = instant.isoformat(timespec='milliseconds').replace('+00:00', 'Z')
            samples.append(CanonicalSensorReading.model_validate({{
                'schemaVersion': '1.0',
                'readingId': f'00000000-0000-4000-8000-{{second:012d}}',
                'source': 'forzy-csv',
                'assetTag': 'MTR-BMB-042',
                'sensorId': 's1',
                'scheduledAt': None,
                'observedAt': timestamp,
                'receivedAt': timestamp,
                'measurements': {{
                    'vibrationVelocityRms': {{
                        'value': 0.1 + second * 0.001,
                        'unit': 'mm/s',
                        'semanticConfidence': 'inferred_from_datasheet',
                    }},
                    'vibrationAcceleration': {{
                        'value': 0.0,
                        'unit': 'g',
                        'statistic': 'unknown',
                        'semanticConfidence': 'unconfirmed',
                    }},
                    'temperature': {{
                        'value': 30.0 + second * 0.01,
                        'unit': 'degC',
                        'semanticConfidence': 'inferred_from_datasheet',
                    }},
                }},
                'qualityFlags': [],
                'payloadHash': f'sha256:{{second:064x}}',
                'raw': {{}},
                'provenance': {{
                    'sourceSystem': 'deploy-runtime-test',
                    'ingestedAt': timestamp,
                }},
            }}))
        result = scorer.assess(samples, now=base + timedelta(seconds=3))
        print(json.dumps(result.model_dump(mode='json', by_alias=True), sort_keys=True))
        """
    )
    env = {
        **os.environ,
        "PYTHONPATH": str(repository_root / "services" / "twinops" / "src"),
    }

    completed = subprocess.run(
        [sys.executable, "-c", command],
        cwd=repository_root,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert completed.returncode == 0, completed.stderr
    return json.loads(completed.stdout)
